class LoginError(Exception):
    pass

class OpenresolvError(Exception):
    pass